### ISSUE TITLE
tests seem to be ES-version specific

### ISSUE THREAD

**Issue by willkg** [pyelasticsearch/pyelasticsearch#107]
There are a bunch of tests that fail for me with Elasticsearch 0.20.4:

```
(pyelasticsearch) (106-info=88950 run_tests.sh) saturn ~/mozilla/pyelasticsearch> ./run_tests.sh 

ERROR: pyelasticsearch.tests.client_tests:IndexingTestCase.test_percolate
  vim +324 pyelasticsearch/tests/client_tests.py  # test_percolate
    result = self.conn.percolate('test-index','test-type', document)
  vim +96  pyelasticsearch/client.py  # decorate
    return func(*args, query_params=query_params, **kwargs)
  vim +984 pyelasticsearch/client.py  # percolate
    doc, query_params=query_params)
  vim +254 pyelasticsearch/client.py  # send_request
    self._raise_exception(resp, prepped_response)
  vim +268 pyelasticsearch/client.py  # _raise_exception
    raise error_class(response.status_code, error_message)
ElasticHttpError: (500, u'NoShardAvailableActionException[[_na][_na] No shard available for [org.elasticsearch.action.percolate.PercolateRequest@25aaaa]]')
-------------------- >> begin captured logging << --------------------
pyelasticsearch: DEBUG: Making a request equivalent to this: curl -XPUT 'http://localhost:9200/test-index' -d 'null'
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): localhost
requests.packages.urllib3.connectionpool: DEBUG: "PUT /test-index HTTP/1.1" 200 31
pyelasticsearch: DEBUG: response status: 200
pyelasticsearch: DEBUG: got response {u'acknowledged': True, u'ok': True}
pyelasticsearch: DEBUG: Making a request equivalent to this: curl -XPUT 'http://localhost:9200/_percolator/test-index/id_1' -d '{"query": {"match": {"name": "Joe"}}}'
requests.packages.urllib3.connectionpool: DEBUG: "PUT /_percolator/test-index/id_1 HTTP/1.1" 201 81
pyelasticsearch: DEBUG: response status: 201
pyelasticsearch: DEBUG: got response {u'_type': u'test-index', u'_id': u'id_1', u'ok': True, u'_version': 1, u'_index': u'_percolator'}
pyelasticsearch: DEBUG: Making a request equivalent to this: curl -XPUT 'http://localhost:9200/_percolator/test-index/id_2' -d '{"query": {"match": {"name": "not_that_guy"}}}'
requests.packages.urllib3.connectionpool: DEBUG: "PUT /_percolator/test-index/id_2 HTTP/1.1" 201 81
pyelasticsearch: DEBUG: response status: 201
pyelasticsearch: DEBUG: got response {u'_type': u'test-index', u'_id': u'id_2', u'ok': True, u'_version': 1, u'_index': u'_percolator'}
pyelasticsearch: DEBUG: Making a request equivalent to this: curl -XGET 'http://localhost:9200/test-index/test-type/_percolate' -d '{"doc": {"name": "Joe"}}'
requests.packages.urllib3.connectionpool: DEBUG: "GET /test-index/test-type/_percolate HTTP/1.1" 500 152
pyelasticsearch: DEBUG: response status: 500
--------------------- >> end captured logging << ---------------------

FAIL: pyelasticsearch.tests.client_tests:SearchTestCase.test_mlt
  vim +402 pyelasticsearch/tests/client_tests.py  # test_mlt
    self.assert_result_contains(result, {'hits': {'hits': [{'_score': 0.19178301, '_type': 'test-type', '_id': '3', '_source': {'name': 'Joe Test'}, '_index': 'test-index'}], 'total': 1, 'max_score': 0.19178301}})
  vim +27  pyelasticsearch/tests/__init__.py  # assert_result_contains
    eq_(value, result[key])
AssertionError: {'hits': [{'_score': 0.19178301, '_type': 'test-type', '_id': '3', '_index': 'test-index', '_source': {'name': 'Joe Test'}}], 'total': 1, 'max_score': 0.19178301} != {u'hits': [{u'_score': 0.18116833, u'_type': u'test-type', u'_id': u'3', u'_source': {u'name': u'Joe Test'}, u'_index': u'test-index'}], u'total': 1, u'max_score': 0.18116833}
-------------------- >> begin captured logging << --------------------
pyelasticsearch: DEBUG: Making a request equivalent to this: curl -XPUT 'http://localhost:9200/test-index/test-type/1' -d '{"name": "Joe Tester"}'
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): localhost
requests.packages.urllib3.connectionpool: DEBUG: "PUT /test-index/test-type/1 HTTP/1.1" 201 76
pyelasticsearch: DEBUG: response status: 201
pyelasticsearch: DEBUG: got response {u'_type': u'test-type', u'_id': u'1', u'ok': True, u'_version': 1, u'_index': u'test-index'}
pyelasticsearch: DEBUG: Making a request equivalent to this: curl -XPUT 'http://localhost:9200/test-index/test-type/2' -d '{"name": "Bill Baloney"}'
requests.packages.urllib3.connectionpool: DEBUG: "PUT /test-index/test-type/2 HTTP/1.1" 201 76
pyelasticsearch: DEBUG: response status: 201
pyelasticsearch: DEBUG: got response {u'_type': u'test-type', u'_id': u'2', u'ok': True, u'_version': 1, u'_index': u'test-index'}
pyelasticsearch: DEBUG: Making a request equivalent to this: curl -XPOST 'http://localhost:9200/test-index/_refresh' -d '""'
requests.packages.urllib3.connectionpool: DEBUG: "POST /test-index/_refresh HTTP/1.1" 200 59
pyelasticsearch: DEBUG: response status: 200
pyelasticsearch: DEBUG: got response {u'ok': True, u'_shards': {u'successful': 1, u'failed': 0, u'total': 1}}
pyelasticsearch: DEBUG: Making a request equivalent to this: curl -XPUT 'http://localhost:9200/test-index/test-type/3' -d '{"name": "Joe Test"}'
requests.packages.urllib3.connectionpool: DEBUG: "PUT /test-index/test-type/3 HTTP/1.1" 201 76
pyelasticsearch: DEBUG: response status: 201
pyelasticsearch: DEBUG: got response {u'_type': u'test-type', u'_id': u'3', u'ok': True, u'_version': 1, u'_index': u'test-index'}
pyelasticsearch: DEBUG: Making a request equivalent to this: curl -XPOST 'http://localhost:9200/test-index/_refresh' -d '""'
requests.packages.urllib3.connectionpool: DEBUG: "POST /test-index/_refresh HTTP/1.1" 200 59
pyelasticsearch: DEBUG: response status: 200
pyelasticsearch: DEBUG: got response {u'ok': True, u'_shards': {u'successful': 1, u'failed': 0, u'total': 1}}
pyelasticsearch: DEBUG: Making a request equivalent to this: curl -XGET 'http://localhost:9200/test-index/test-type/1/_mlt?min_doc_freq=1&mlt_fields=name&min_term_freq=1' -d '""'
requests.packages.urllib3.connectionpool: DEBUG: "GET /test-index/test-type/1/_mlt?min_doc_freq=1&mlt_fields=name&min_term_freq=1 HTTP/1.1" 200 235
pyelasticsearch: DEBUG: response status: 200
pyelasticsearch: DEBUG: got response {u'hits': {u'hits': [{u'_score': 0.18116833, u'_type': u'test-type', u'_id': u'3', u'_source': {u'name': u'Joe Test'}, u'_index': u'test-index'}], u'total': 1, u'max_score': 0.18116833}, u'_shards': {u'successful': 1, u'failed': 0, u'total': 1}, u'took': 1, u'timed_out': False}
--------------------- >> end captured logging << ---------------------

FAIL: pyelasticsearch.tests.client_tests:SearchTestCase.test_mlt_fields
  vim +435 pyelasticsearch/tests/client_tests.py  # test_mlt_fields
    {u'hits': {u'hits': [{u'_score': 0.30685282, u'_type': u'test-type', u'_id': u'4', u'_source': {u'sport': u'football', u'name': u'Cam'}, u'_index': u'test-index'}], u'total': 1, u'max_score': 0.30685282}})
  vim +27  pyelasticsearch/tests/__init__.py  # assert_result_contains
    eq_(value, result[key])
AssertionError: {u'hits': [{u'_score': 0.30685282, u'_type': u'test-type', u'_id': u'4', u'_index': u'test-index', u'_source': {u'sport': u'football', u'name': u'Cam'}}], u'total': 1, u'max_score': 0.30685282} != {u'hits': [{u'_score': 1.5108256, u'_type': u'test-type', u'_id': u'4', u'_source': {u'sport': u'football', u'name': u'Cam'}, u'_index': u'test-index'}], u'total': 1, u'max_score': 1.5108256}
-------------------- >> begin captured logging << --------------------
pyelasticsearch: DEBUG: Making a request equivalent to this: curl -XPUT 'http://localhost:9200/test-index/test-type/1' -d '{"name": "Joe Tester"}'
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): localhost
requests.packages.urllib3.connectionpool: DEBUG: "PUT /test-index/test-type/1 HTTP/1.1" 201 76
pyelasticsearch: DEBUG: response status: 201
pyelasticsearch: DEBUG: got response {u'_type': u'test-type', u'_id': u'1', u'ok': True, u'_version': 1, u'_index': u'test-index'}
pyelasticsearch: DEBUG: Making a request equivalent to this: curl -XPUT 'http://localhost:9200/test-index/test-type/2' -d '{"name": "Bill Baloney"}'
requests.packages.urllib3.connectionpool: DEBUG: "PUT /test-index/test-type/2 HTTP/1.1" 201 76
pyelasticsearch: DEBUG: response status: 201
pyelasticsearch: DEBUG: got response {u'_type': u'test-type', u'_id': u'2', u'ok': True, u'_version': 1, u'_index': u'test-index'}
pyelasticsearch: DEBUG: Making a request equivalent to this: curl -XPOST 'http://localhost:9200/test-index/_refresh' -d '""'
requests.packages.urllib3.connectionpool: DEBUG: "POST /test-index/_refresh HTTP/1.1" 200 59
pyelasticsearch: DEBUG: response status: 200
pyelasticsearch: DEBUG: got response {u'ok': True, u'_shards': {u'successful': 1, u'failed': 0, u'total': 1}}
pyelasticsearch: DEBUG: Making a request equivalent to this: curl -XPUT 'http://localhost:9200/test-index/test-type/3' -d '{"sport": "football", "name": "Angus"}'
requests.packages.urllib3.connectionpool: DEBUG: "PUT /test-index/test-type/3 HTTP/1.1" 201 76
pyelasticsearch: DEBUG: response status: 201
pyelasticsearch: DEBUG: got response {u'_type': u'test-type', u'_id': u'3', u'ok': True, u'_version': 1, u'_index': u'test-index'}
pyelasticsearch: DEBUG: Making a request equivalent to this: curl -XPUT 'http://localhost:9200/test-index/test-type/4' -d '{"sport": "football", "name": "Cam"}'
requests.packages.urllib3.connectionpool: DEBUG: "PUT /test-index/test-type/4 HTTP/1.1" 201 76
pyelasticsearch: DEBUG: response status: 201
pyelasticsearch: DEBUG: got response {u'_type': u'test-type', u'_id': u'4', u'ok': True, u'_version': 1, u'_index': u'test-index'}
pyelasticsearch: DEBUG: Making a request equivalent to this: curl -XPUT 'http://localhost:9200/test-index/test-type/5' -d '{"sport": "baseball", "name": "Sophia"}'
requests.packages.urllib3.connectionpool: DEBUG: "PUT /test-index/test-type/5 HTTP/1.1" 201 76
pyelasticsearch: DEBUG: response status: 201
pyelasticsearch: DEBUG: got response {u'_type': u'test-type', u'_id': u'5', u'ok': True, u'_version': 1, u'_index': u'test-index'}
pyelasticsearch: DEBUG: Making a request equivalent to this: curl -XPOST 'http://localhost:9200/test-index/_refresh' -d '""'
requests.packages.urllib3.connectionpool: DEBUG: "POST /test-index/_refresh HTTP/1.1" 200 59
pyelasticsearch: DEBUG: response status: 200
pyelasticsearch: DEBUG: got response {u'ok': True, u'_shards': {u'successful': 1, u'failed': 0, u'total': 1}}
pyelasticsearch: DEBUG: Making a request equivalent to this: curl -XGET 'http://localhost:9200/test-index/test-type/3/_mlt?min_doc_freq=1&mlt_fields=sport&min_term_freq=1' -d '""'
requests.packages.urllib3.connectionpool: DEBUG: "GET /test-index/test-type/3/_mlt?min_doc_freq=1&mlt_fields=sport&min_term_freq=1 HTTP/1.1" 200 249
pyelasticsearch: DEBUG: response status: 200
pyelasticsearch: DEBUG: got response {u'hits': {u'hits': [{u'_score': 1.5108256, u'_type': u'test-type', u'_id': u'4', u'_source': {u'sport': u'football', u'name': u'Cam'}, u'_index': u'test-index'}], u'total': 1, u'max_score': 1.5108256}, u'_shards': {u'successful': 1, u'failed': 0, u'total': 1}, u'took': 1, u'timed_out': False}
--------------------- >> end captured logging << ---------------------

FAIL: pyelasticsearch.tests.client_tests:SearchTestCase.test_mlt_with_body
  vim +424 pyelasticsearch/tests/client_tests.py  # test_mlt_with_body
    {'hits': {'hits': [{'_score': 0.19178301, '_type': 'test-type', '_id': '3', '_source': {'age': 16, 'name': 'Joe Justin'}, '_index': 'test-index'}], 'total': 1, 'max_score': 0.19178301}})
  vim +27  pyelasticsearch/tests/__init__.py  # assert_result_contains
    eq_(value, result[key])
AssertionError: {'hits': [{'_score': 0.19178301, '_type': 'test-type', '_id': '3', '_index': 'test-index', '_source': {'age': 16, 'name': 'Joe Justin'}}], 'total': 1, 'max_score': 0.19178301} != {u'hits': [{u'_score': 0.15891947, u'_type': u'test-type', u'_id': u'3', u'_source': {u'age': 16, u'name': u'Joe Justin'}, u'_index': u'test-index'}], u'total': 1, u'max_score': 0.15891947}
-------------------- >> begin captured logging << --------------------
pyelasticsearch: DEBUG: Making a request equivalent to this: curl -XPUT 'http://localhost:9200/test-index/test-type/1' -d '{"name": "Joe Tester"}'
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): localhost
requests.packages.urllib3.connectionpool: DEBUG: "PUT /test-index/test-type/1 HTTP/1.1" 201 76
pyelasticsearch: DEBUG: response status: 201
pyelasticsearch: DEBUG: got response {u'_type': u'test-type', u'_id': u'1', u'ok': True, u'_version': 1, u'_index': u'test-index'}
pyelasticsearch: DEBUG: Making a request equivalent to this: curl -XPUT 'http://localhost:9200/test-index/test-type/2' -d '{"name": "Bill Baloney"}'
requests.packages.urllib3.connectionpool: DEBUG: "PUT /test-index/test-type/2 HTTP/1.1" 201 76
pyelasticsearch: DEBUG: response status: 201
pyelasticsearch: DEBUG: got response {u'_type': u'test-type', u'_id': u'2', u'ok': True, u'_version': 1, u'_index': u'test-index'}
pyelasticsearch: DEBUG: Making a request equivalent to this: curl -XPOST 'http://localhost:9200/test-index/_refresh' -d '""'
requests.packages.urllib3.connectionpool: DEBUG: "POST /test-index/_refresh HTTP/1.1" 200 59
pyelasticsearch: DEBUG: response status: 200
pyelasticsearch: DEBUG: got response {u'ok': True, u'_shards': {u'successful': 1, u'failed': 0, u'total': 1}}
pyelasticsearch: DEBUG: Making a request equivalent to this: curl -XPUT 'http://localhost:9200/test-index/test-type/2' -d '{"age": 22, "name": "Joe Test"}'
requests.packages.urllib3.connectionpool: DEBUG: "PUT /test-index/test-type/2 HTTP/1.1" 200 76
pyelasticsearch: DEBUG: response status: 200
pyelasticsearch: DEBUG: got response {u'_type': u'test-type', u'_id': u'2', u'ok': True, u'_version': 2, u'_index': u'test-index'}
pyelasticsearch: DEBUG: Making a request equivalent to this: curl -XPUT 'http://localhost:9200/test-index/test-type/3' -d '{"age": 16, "name": "Joe Justin"}'
requests.packages.urllib3.connectionpool: DEBUG: "PUT /test-index/test-type/3 HTTP/1.1" 201 76
pyelasticsearch: DEBUG: response status: 201
pyelasticsearch: DEBUG: got response {u'_type': u'test-type', u'_id': u'3', u'ok': True, u'_version': 1, u'_index': u'test-index'}
pyelasticsearch: DEBUG: Making a request equivalent to this: curl -XPOST 'http://localhost:9200/test-index/_refresh' -d '""'
requests.packages.urllib3.connectionpool: DEBUG: "POST /test-index/_refresh HTTP/1.1" 200 59
pyelasticsearch: DEBUG: response status: 200
pyelasticsearch: DEBUG: got response {u'ok': True, u'_shards': {u'successful': 1, u'failed': 0, u'total': 1}}
pyelasticsearch: DEBUG: Making a request equivalent to this: curl -XGET 'http://localhost:9200/test-index/test-type/1/_mlt?min_doc_freq=1&mlt_fields=name&min_term_freq=1' -d '{"filter": {"fquery": {"query": {"range": {"age": {"to": 20, "from": 10}}}}}}'
requests.packages.urllib3.connectionpool: DEBUG: "GET /test-index/test-type/1/_mlt?min_doc_freq=1&mlt_fields=name&min_term_freq=1 HTTP/1.1" 200 248
pyelasticsearch: DEBUG: response status: 200
pyelasticsearch: DEBUG: got response {u'hits': {u'hits': [{u'_score': 0.15891947, u'_type': u'test-type', u'_id': u'3', u'_source': {u'age': 16, u'name': u'Joe Justin'}, u'_index': u'test-index'}], u'total': 1, u'max_score': 0.15891947}, u'_shards': {u'successful': 1, u'failed': 0, u'total': 1}, u'took': 2, u'timed_out': False}
--------------------- >> end captured logging << ---------------------

FAIL: pyelasticsearch.tests.client_tests:SearchTestCase.test_search_by_field
  vim +362 pyelasticsearch/tests/client_tests.py  # test_search_by_field
    self.assert_result_contains(result, {'hits': {'hits': [{'_score': 0.19178301, '_type': 'test-type', '_id': '1', '_source': {'name': 'Joe Tester'}, '_index': 'test-index'}], 'total': 1, 'max_score': 0.19178301}})
  vim +27  pyelasticsearch/tests/__init__.py  # assert_result_contains
    eq_(value, result[key])
AssertionError: {'hits': [{'_score': 0.19178301, '_type': 'test-type', '_id': '1', '_index': 'test-index', '_source': {'name': 'Joe Tester'}}], 'total': 1, 'max_score': 0.19178301} != {u'hits': [{u'_score': 0.625, u'_type': u'test-type', u'_id': u'1', u'_source': {u'name': u'Joe Tester'}, u'_index': u'test-index'}], u'total': 1, u'max_score': 0.625}
-------------------- >> begin captured logging << --------------------
pyelasticsearch: DEBUG: Making a request equivalent to this: curl -XPUT 'http://localhost:9200/test-index/test-type/1' -d '{"name": "Joe Tester"}'
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): localhost
requests.packages.urllib3.connectionpool: DEBUG: "PUT /test-index/test-type/1 HTTP/1.1" 201 76
pyelasticsearch: DEBUG: response status: 201
pyelasticsearch: DEBUG: got response {u'_type': u'test-type', u'_id': u'1', u'ok': True, u'_version': 1, u'_index': u'test-index'}
pyelasticsearch: DEBUG: Making a request equivalent to this: curl -XPUT 'http://localhost:9200/test-index/test-type/2' -d '{"name": "Bill Baloney"}'
requests.packages.urllib3.connectionpool: DEBUG: "PUT /test-index/test-type/2 HTTP/1.1" 201 76
pyelasticsearch: DEBUG: response status: 201
pyelasticsearch: DEBUG: got response {u'_type': u'test-type', u'_id': u'2', u'ok': True, u'_version': 1, u'_index': u'test-index'}
pyelasticsearch: DEBUG: Making a request equivalent to this: curl -XPOST 'http://localhost:9200/test-index/_refresh' -d '""'
requests.packages.urllib3.connectionpool: DEBUG: "POST /test-index/_refresh HTTP/1.1" 200 59
pyelasticsearch: DEBUG: response status: 200
pyelasticsearch: DEBUG: got response {u'ok': True, u'_shards': {u'successful': 1, u'failed': 0, u'total': 1}}
pyelasticsearch: DEBUG: Making a request equivalent to this: curl -XGET 'http://localhost:9200/test-index/_search?q=name%3Ajoe' -d '""'
requests.packages.urllib3.connectionpool: DEBUG: "GET /test-index/_search?q=name%3Ajoe HTTP/1.1" 200 227
pyelasticsearch: DEBUG: response status: 200
pyelasticsearch: DEBUG: got response {u'hits': {u'hits': [{u'_score': 0.625, u'_type': u'test-type', u'_id': u'1', u'_source': {u'name': u'Joe Tester'}, u'_index': u'test-index'}], u'total': 1, u'max_score': 0.625}, u'_shards': {u'successful': 1, u'failed': 0, u'total': 1}, u'took': 1, u'timed_out': False}
--------------------- >> end captured logging << ---------------------

60 tests, 4 failures, 1 error in 11.6s

real	0m11.895s
user	0m0.796s
sys	0m0.092s
```

I'm pretty sure the failures are all related to different scores in the actual results than in the expected results.

I mentioned this to @erikrose a while back and then either he or I mentioned that it could be due to different Elasticsearch versions.

Anyhow, two things:

1. is this from different Elasticsearch versions?
2. if so, how do we change the tests so they're not finicky about the actual score numbers?

**Comment by willkg** [comment]
Update to this. I'm using Elasticsearch 0.90 and seeing these errors:

```
======================================================================
FAIL: test_mlt (pyelasticsearch.tests.client_tests.SearchTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/willkg/mozilla/pyelasticsearch/pyelasticsearch/tests/client_tests.py", line 404, in test_mlt
    self.assert_result_contains(result, {'hits': {'hits': [{'_score': 0.19178301, '_type': 'test-type', '_id': '3', '_source': {'name': 'Joe Test'}, '_index': 'test-index'}], 'total': 1, 'max_score': 0.19178301}})
  File "/home/willkg/mozilla/pyelasticsearch/pyelasticsearch/tests/__init__.py", line 27, in assert_result_contains
    eq_(value, result[key])
AssertionError: {'hits': [{'_score': 0.19178301, '_type': 'test-type', '_id': '3', '_index': 'test-index', '_source': {'name': 'Joe Test'}}], 'total': 1, 'max_score': 0.19178301} != {u'hits': [{u'_score': 0.18116833, u'_type': u'test-type', u'_id': u'3', u'_source': {u'name': u'Joe Test'}, u'_index': u'test-index'}], u'total': 1, u'max_score': 0.18116833}

======================================================================
FAIL: test_mlt_fields (pyelasticsearch.tests.client_tests.SearchTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/willkg/mozilla/pyelasticsearch/pyelasticsearch/tests/client_tests.py", line 437, in test_mlt_fields
    {u'hits': {u'hits': [{u'_score': 0.30685282, u'_type': u'test-type', u'_id': u'4', u'_source': {u'sport': u'football', u'name': u'Cam'}, u'_index': u'test-index'}], u'total': 1, u'max_score': 0.30685282}})
  File "/home/willkg/mozilla/pyelasticsearch/pyelasticsearch/tests/__init__.py", line 27, in assert_result_contains
    eq_(value, result[key])
AssertionError: {u'hits': [{u'_score': 0.30685282, u'_type': u'test-type', u'_id': u'4', u'_index': u'test-index', u'_source': {u'sport': u'football', u'name': u'Cam'}}], u'total': 1, u'max_score': 0.30685282} != {u'hits': [{u'_score': 1.5108256, u'_type': u'test-type', u'_id': u'4', u'_source': {u'sport': u'football', u'name': u'Cam'}, u'_index': u'test-index'}], u'total': 1, u'max_score': 1.5108256}

======================================================================
FAIL: test_mlt_with_body (pyelasticsearch.tests.client_tests.SearchTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/willkg/mozilla/pyelasticsearch/pyelasticsearch/tests/client_tests.py", line 426, in test_mlt_with_body
    {'hits': {'hits': [{'_score': 0.19178301, '_type': 'test-type', '_id': '3', '_source': {'age': 16, 'name': 'Joe Justin'}, '_index': 'test-index'}], 'total': 1, 'max_score': 0.19178301}})
  File "/home/willkg/mozilla/pyelasticsearch/pyelasticsearch/tests/__init__.py", line 27, in assert_result_contains
    eq_(value, result[key])
AssertionError: {'hits': [{'_score': 0.19178301, '_type': 'test-type', '_id': '3', '_index': 'test-index', '_source': {'age': 16, 'name': 'Joe Justin'}}], 'total': 1, 'max_score': 0.19178301} != {u'hits': [{u'_score': 0.15891947, u'_type': u'test-type', u'_id': u'3', u'_source': {u'age': 16, u'name': u'Joe Justin'}, u'_index': u'test-index'}], u'total': 1, u'max_score': 0.15891947}

======================================================================
FAIL: test_search_by_field (pyelasticsearch.tests.client_tests.SearchTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/willkg/mozilla/pyelasticsearch/pyelasticsearch/tests/client_tests.py", line 364, in test_search_by_field
    self.assert_result_contains(result, {'hits': {'hits': [{'_score': 0.19178301, '_type': 'test-type', '_id': '1', '_source': {'name': 'Joe Tester'}, '_index': 'test-index'}], 'total': 1, 'max_score': 0.19178301}})
  File "/home/willkg/mozilla/pyelasticsearch/pyelasticsearch/tests/__init__.py", line 27, in assert_result_contains
    eq_(value, result[key])
AssertionError: {'hits': [{'_score': 0.19178301, '_type': 'test-type', '_id': '1', '_index': 'test-index', '_source': {'name': 'Joe Tester'}}], 'total': 1, 'max_score': 0.19178301} != {u'hits': [{u'_score': 0.625, u'_type': u'test-type', u'_id': u'1', u'_source': {u'name': u'Joe Tester'}, u'_index': u'test-index'}], u'total': 1, u'max_score': 0.625}
```

Grabbing this one to fix now since it alleviates problems with fixing other things.
