### ISSUE TITLE
ElasticSearch.delete_by_query broken with ES 1.0+

### ISSUE THREAD

**Issue by willkg** [pyelasticsearch/pyelasticsearch#156]
Here's the failing test with Elasticsearch 1.0.3:

```
======================================================================
ERROR: pyelasticsearch/tests/client_tests.py:IndexingTestCase.test_delete_by_query
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/willkg/mozilla/pyelasticsearch/pyelasticsearch/tests/client_tests.py", line 161, in test_delete_by_query
    result = self.conn.delete_by_query('test-index', 'test-type', {'query_string': {'query': 'name:joe OR name:bill'}})
  File "/home/willkg/mozilla/pyelasticsearch/pyelasticsearch/client.py", line 96, in decorate
    return func(*args, query_params=query_params, **kwargs)
  File "/home/willkg/mozilla/pyelasticsearch/pyelasticsearch/client.py", line 458, in delete_by_query
    query_params=query_params)
  File "/home/willkg/mozilla/pyelasticsearch/pyelasticsearch/client.py", line 254, in send_request
    self._raise_exception(resp, prepped_response)
  File "/home/willkg/mozilla/pyelasticsearch/pyelasticsearch/client.py", line 265, in _raise_exception
    elif (error_message.startswith('IndexAlreadyExistsException') or
AttributeError: 'dict' object has no attribute 'startswith'
```

**Comment by erikrose** [comment]
Fixed in 9571b2f13027a26b4c124a9194bac04a4f9703f2.
