### ISSUE TITLE
ElasticSearch.percolate broken with ES 1.0+

### ISSUE THREAD

**Issue by willkg** [pyelasticsearch/pyelasticsearch#157]
Here's the failing test with Elasticsearch 1.0.3:

```
======================================================================
ERROR: pyelasticsearch/tests/client_tests.py:IndexingTestCase.test_percolate
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/willkg/mozilla/pyelasticsearch/pyelasticsearch/tests/client_tests.py", line 345, in test_percolate
    id='id_1')
  File "/home/willkg/mozilla/pyelasticsearch/pyelasticsearch/client.py", line 96, in decorate
    return func(*args, query_params=query_params, **kwargs)
  File "/home/willkg/mozilla/pyelasticsearch/pyelasticsearch/client.py", line 344, in index
    query_params)
  File "/home/willkg/mozilla/pyelasticsearch/pyelasticsearch/client.py", line 254, in send_request
    self._raise_exception(resp, prepped_response)
  File "/home/willkg/mozilla/pyelasticsearch/pyelasticsearch/client.py", line 269, in _raise_exception
    raise error_class(response.status_code, error_message)
ElasticHttpError: (400, u"InvalidIndexNameException[[_percolator] Invalid index name [_percolator], must not start with '_']")
```

**Comment by erikrose** [comment]
Fixed in b1a605f044d0d0534c57cd57e7d76e454bb366b0.
