### ISSUE TITLE
pyelasticsearch failing on port 80 with version 1.0

### ISSUE THREAD

**Issue by jogo** [pyelasticsearch/pyelasticsearch#162]
Previously pyelasticsearch didn't add a default port of 9200, so we were able to use the URL http://logstash.openstack.org/elasticsearch/ as short hand for http://logstash.openstack.org:80/elasticsearch/, instead of http://logstash.openstack.org:9200/elasticsearch/.

Now if we specify port 80 we get:

    import pyelasticsearch as es
    es.ElasticSearch("http://logstash.openstack.org:80/elasticsearch").search("")

output:

    WARNING:elasticsearch:GET /_search?q= [status:404 request:0.313s]
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/.tox/venv/local/lib/python2.7/site-packages/pyelasticsearch/client.py", line 88, in decorate
        return func(*args, query_params=query_params, **kwargs)
      File "/.tox/venv/local/lib/python2.7/site-packages/pyelasticsearch/client.py", line 563, in search
        return self._search_or_count('_search', query, **kwargs)
      File ".tox/venv/local/lib/python2.7/site-packages/pyelasticsearch/client.py", line 540, in _search_or_count
        query_params=query_params)
      File ".tox/venv/local/lib/python2.7/site-packages/pyelasticsearch/client.py", line 236, in send_request
        self._raise_exception(status, error_message)
      File ".tox/venv/local/lib/python2.7/site-packages/pyelasticsearch/client.py", line 250, in _raise_exception
        raise error_class(status, error_message)
    pyelasticsearch.exceptions.ElasticHttpNotFoundError: (404, u'<!DOCTYPE html>\n<html>\n<head>\n  <style type="text/css">\n  body { text-align:center;font-family:helvetica,arial;font-size:22px;\n    color:#888;margin:20px}\n  #c {margin:0 auto;width:500px;text-align:left}\n  </style>\n</head>\n<body>\n  <h2>Sinatra doesn&rsquo;t know this ditty.</h2>\n  <img src=\'http://logstash.openstack.org/__sinatra__/404.png\'>\n  <div id="c">\n    Try this:\n    <pre>get \'/_search\' do\n  "Hello World"\nend</pre>\n  </div>\n</body>\n</html>\n')

**Comment by ftarnell** [comment]
I believe the actual cause of this is that at some point between 0.6 and 1.2, support for a path in the URL was broken.  When configured with a URL of `http://localhost:8938/es1.3/`, pyelasticsearch will try to access `http://localhost:8938/<indexname>/...` instead of `http://localhost:8938/es1.3/<indexname>/...`.

That matches the URL path in OP's error: `WARNING:elasticsearch:GET /_search?q= `.
